import { CockroachDbContainer } from "@testcontainers/cockroachdb";
import { KyrageDialect } from "./types";
import { Pool } from "pg";
import { DBClient } from "../client";
import {
  Kysely,
  MigrationLockOptions,
  PostgresAdapter,
  PostgresDialect,
} from "kysely";
import {
  convertPSQLTypeName,
  introspectPSQLConstraints,
  introspectPSQLIndexes,
  introspectPSQLTables,
  removeAutoGeneratedIndexesFromUniqueConstraints,
} from "./postgres";

export class CockroachDBKyrageDialect implements KyrageDialect {
  getName() {
    return "cockroachdb" as const;
  }

  getDevDatabaseImageName() {
    return "cockroachdb/cockroach:latest-v24.3";
  }

  createKyselyDialect(connectionString: string) {
    return new CockroachDBDialect({
      pool: new Pool({ connectionString }),
    });
  }

  createIntrospectionDriver(client: DBClient) {
    return {
      convertTypeName: convertPSQLTypeName,
      introspect: async () => {
        await using db = client.getDB();
        const tables = await introspectPSQLTables(db);
        const indexes = await introspectPSQLIndexes(db);
        const constraints = await introspectPSQLConstraints(db);
        const nomalizedIndexes =
          removeAutoGeneratedIndexesFromUniqueConstraints(indexes, constraints);

        return {
          tables,
          indexes: nomalizedIndexes,
          constraints,
        };
      },
    };
  }

  createDevDatabaseContainer(image: string) {
    return new CockroachDbContainer(image);
  }
}

// Ref: https://github.com/kysely-org/kysely/issues/325#issuecomment-1426878934
class CockroachDBAdapter extends PostgresAdapter {
  override async acquireMigrationLock(
    db: Kysely<any>,
    options: MigrationLockOptions
  ) {
    await db.selectFrom(options.lockTable).selectAll().forUpdate().execute();
  }
}

export class CockroachDBDialect extends PostgresDialect {
  override createAdapter() {
    return new CockroachDBAdapter();
  }
}
