import { MysqlDialect, sql, type MysqlPool } from "kysely";
import { createPool } from "mysql2";
import type { IntrospectProps, KyrageDialect } from "./types";
import type { DBClient, PlannableKysely } from "../client";
import type { ReferentialActions } from "../operations/shared/types";
import { computeAutoGeneratedIndexesAndConstraints } from "./shared";
import { mysqlSchemaAdapter } from "./mysql-schema-adapter";
import { hasRunningDevStartContainer } from "../dev/providers/container";
import type { DevDatabaseConfig, DevDatabaseProvider } from "../dev/types";

/** Shares connections, schema behavior, and introspection across MySQL-compatible dialects. */
export abstract class MysqlCompatibleKyrageDialect implements KyrageDialect {
  /** Identifies the concrete database for configuration and container reuse. */
  abstract getName(): "mysql" | "mariadb";

  /** Supplies the concrete database's development container. */
  abstract createDevDatabaseProvider(): DevDatabaseProvider;

  /** Applies concrete database defaults to development configuration. */
  abstract parseDevDatabaseConfig(config: unknown): DevDatabaseConfig;

  /** Creates a MySQL-compatible Kysely connection using mysql2. */
  createKyselyDialect(connectionString: string) {
    return new MysqlDialect({
      pool: createPool(connectionString) as unknown as MysqlPool,
    });
  }

  /** Uses shared MySQL/MariaDB schema comparison and operation behavior. */
  createSchemaAdapter() {
    return mysqlSchemaAdapter;
  }

  /** Supplies the shared catalog queries and type conversion. */
  createIntrospectionDriver(client: DBClient) {
    return {
      convertTypeName: convertMysqlTypeName,
      introspect: doMysqlIntrospect(client),
    };
  }

  /** Finds reusable containers belonging to the concrete dialect. */
  async hasReusableDevDatabase() {
    return hasRunningDevStartContainer(this.getName());
  }
}

/** Normalizes catalog metadata without dropping implicit foreign-key indexes. */
export const doMysqlIntrospect =
  (client: DBClient) => async (props: IntrospectProps) => {
    await using db = client.getDB();
    const [tables, indexes, constraints] = await Promise.all([
      introspectMysqlTables(db),
      introspectMysqlIndexes(db),
      introspectMysqlConstraints(db),
    ]);
    const normalized = computeAutoGeneratedIndexesAndConstraints(props.config, {
      indexes,
      constraints,
    });

    // Caveat: index provenance is unavailable; infer implicit FK indexes by name.
    // Declare the index explicitly to manage it independently of its constraint.
    const normalizedIndexes = normalized.indexes.filter(
      (index) =>
        props.config.indexes.some(
          (configured) =>
            configured.table === index.table && configured.name === index.name,
        ) ||
        !constraints.foreignKey.some(
          (fk) =>
            !index.unique &&
            fk.table === index.table &&
            fk.name === index.name &&
            fk.columns.every(
              (column, position) => index.columns[position] === column,
            ) &&
            props.config.foreignKeyConstraints.some(
              (configured) =>
                configured.table === fk.table &&
                configured.name === fk.name &&
                configured.columns.length === fk.columns.length &&
                configured.columns.every(
                  (column, position) => fk.columns[position] === column,
                ),
            ),
        ),
    );

    return {
      tables,
      indexes: normalizedIndexes,
      constraints: {
        ...constraints,
        unique: normalized.uniqueConstraints,
      },
    };
  };

/** Preserves type modifiers, discarding only integer display widths and SQL aliases. */
export const convertMysqlTypeName = (typeName: string) => {
  const normalized = typeName.toLowerCase().replace(/,\s*/g, ", ");
  if (normalized === "tinyint(1)") return "boolean";
  const withoutDisplayWidth = normalized.replace(
    /^(tinyint|smallint|mediumint|int|bigint)\(\d+\)/,
    "$1",
  );
  const nameDict: Record<string, string> = {
    int: "integer",
    double: "double precision",
  };
  return nameDict[withoutDisplayWidth] ?? withoutDisplayWidth;
};

/** Reads full column types and SQL default expressions from the current database. */
export const introspectMysqlTables = async (db: PlannableKysely) => {
  const { rows } = await sql`
    SELECT
      c.TABLE_SCHEMA as table_schema,
      c.TABLE_NAME as table_name,
      c.COLUMN_NAME as column_name,
      c.COLUMN_TYPE as column_type,
      CASE
        WHEN VERSION() LIKE '%MariaDB%' THEN NULLIF(c.COLUMN_DEFAULT, 'NULL')
        WHEN c.EXTRA LIKE '%DEFAULT_GENERATED%' AND c.COLUMN_DEFAULT IS NOT NULL
          THEN CONCAT('(', c.COLUMN_DEFAULT, ')')
        WHEN c.COLUMN_DEFAULT IS NOT NULL
          AND c.DATA_TYPE IN ('char', 'varchar', 'text', 'tinytext', 'mediumtext', 'longtext',
                              'binary', 'varbinary', 'date', 'datetime', 'time', 'timestamp')
          THEN QUOTE(c.COLUMN_DEFAULT)
        ELSE c.COLUMN_DEFAULT
      END as column_default,
      c.CHARACTER_MAXIMUM_LENGTH as character_maximum_length,
      c.EXTRA as extra,
      c.COLUMN_COMMENT as column_comment,
      c.COLLATION_NAME != t.TABLE_COLLATION as custom_collation
    FROM information_schema.COLUMNS c
    JOIN information_schema.TABLES t
      ON c.TABLE_SCHEMA = t.TABLE_SCHEMA AND c.TABLE_NAME = t.TABLE_NAME
    WHERE c.TABLE_SCHEMA = DATABASE()
    ORDER BY c.TABLE_NAME, c.ORDINAL_POSITION;
  `
    .$castTo<MysqlColumnInfo>()
    .execute(db);

  return rows.map((row) => {
    const extra = (row.extra ?? "")
      .replace(/\bDEFAULT_GENERATED\b/g, "")
      .trim();
    const blockedAttributes = [
      extra,
      row.column_comment ? "column comment" : "",
      row.custom_collation ? "custom collation" : "",
    ]
      .filter(Boolean)
      .join(", ");
    return {
      schema: row.table_schema,
      table: row.table_name,
      name: row.column_name,
      dataType: convertMysqlTypeName(row.column_type),
      default: row.column_default,
      characterMaximumLength:
        row.character_maximum_length == null
          ? null
          : Number(row.character_maximum_length),
      ...(blockedAttributes
        ? { alterationBlockedReason: blockedAttributes }
        : {}),
    };
  });
};

/** Raw column metadata, including modifiers omitted by Kysely's introspector. */
type MysqlColumnInfo = {
  table_schema: string;
  table_name: string;
  column_name: string;
  column_type: string;
  column_default: string | null;
  character_maximum_length: number | null;
  extra: string;
  column_comment: string;
  custom_collation: number | null;
};

/** Reads ordered index columns without GROUP_CONCAT truncation or delimiter ambiguity. */
export const introspectMysqlIndexes = async (db: PlannableKysely) => {
  const { rows } = await sql`
    SELECT
      TABLE_NAME as table_name,
      INDEX_NAME as index_name,
      NON_UNIQUE = 0 as is_unique,
      COLUMN_NAME as column_name
    FROM information_schema.STATISTICS
    WHERE TABLE_SCHEMA = DATABASE() AND INDEX_NAME != 'PRIMARY'
    ORDER BY TABLE_NAME, INDEX_NAME, SEQ_IN_INDEX;
  `
    .$castTo<MysqlIndexInfo>()
    .execute(db);

  const indexes = new Map<
    string,
    {
      table: string;
      name: string;
      columns: string[];
      unique: boolean;
    }
  >();
  for (const row of rows) {
    // Expression indexes have no column name and cannot be declared through this API.
    if (row.column_name === null) continue;
    const key = JSON.stringify([row.table_name, row.index_name]);
    const index = indexes.get(key) ?? {
      table: row.table_name,
      name: row.index_name,
      columns: [],
      unique: Boolean(row.is_unique),
    };
    index.columns.push(row.column_name);
    indexes.set(key, index);
  }
  return [...indexes.values()];
};

/** One row per index column, already sorted by its position in the index. */
type MysqlIndexInfo = {
  table_name: string;
  index_name: string;
  is_unique: number;
  column_name: string | null;
};

/** Reads primary, unique, and foreign keys with ordered local and referenced columns. */
export const introspectMysqlConstraints = async (db: PlannableKysely) => {
  const { rows } = await sql`
    SELECT
      tc.TABLE_SCHEMA as schema_name,
      tc.TABLE_NAME as table_name,
      tc.CONSTRAINT_NAME as constraint_name,
      tc.CONSTRAINT_TYPE as constraint_type,
      kcu.COLUMN_NAME as column_name,
      kcu.REFERENCED_TABLE_NAME as referenced_table,
      kcu.REFERENCED_COLUMN_NAME as referenced_column,
      rc.UPDATE_RULE as on_update,
      rc.DELETE_RULE as on_delete
    FROM information_schema.TABLE_CONSTRAINTS tc
    JOIN information_schema.KEY_COLUMN_USAGE kcu
      ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
      AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
      AND tc.TABLE_NAME = kcu.TABLE_NAME
    LEFT JOIN information_schema.REFERENTIAL_CONSTRAINTS rc
      ON tc.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
      AND tc.TABLE_SCHEMA = rc.CONSTRAINT_SCHEMA
      AND tc.TABLE_NAME = rc.TABLE_NAME
    WHERE tc.TABLE_SCHEMA = DATABASE()
      AND tc.CONSTRAINT_TYPE IN ('PRIMARY KEY', 'UNIQUE', 'FOREIGN KEY')
    ORDER BY tc.TABLE_NAME, tc.CONSTRAINT_NAME, kcu.ORDINAL_POSITION;
  `
    .$castTo<MysqlConstraint>()
    .execute(db);

  const grouped = new Map<
    string,
    MysqlConstraint & {
      columns: string[];
      referencedColumns: string[];
    }
  >();
  for (const row of rows) {
    const key = JSON.stringify([row.table_name, row.constraint_name]);
    const constraint = grouped.get(key) ?? {
      ...row,
      columns: [],
      referencedColumns: [],
    };
    constraint.columns.push(row.column_name);
    if (row.referenced_column !== null) {
      constraint.referencedColumns.push(row.referenced_column);
    }
    grouped.set(key, constraint);
  }
  const constraints = [...grouped.values()];
  const attributes = (row: (typeof constraints)[number]) => ({
    schema: row.schema_name,
    table: row.table_name,
    name: row.constraint_name,
    columns: row.columns,
  });

  return {
    primaryKey: constraints
      .filter((row) => row.constraint_type === "PRIMARY KEY")
      .map((row) => ({ ...attributes(row), type: "PRIMARY KEY" as const })),
    unique: constraints
      .filter((row) => row.constraint_type === "UNIQUE")
      .map((row) => ({ ...attributes(row), type: "UNIQUE" as const })),
    foreignKey: constraints
      .filter((row) => row.constraint_type === "FOREIGN KEY")
      .map((row) => ({
        ...attributes(row),
        type: "FOREIGN KEY" as const,
        referencedTable: row.referenced_table!,
        referencedColumns: row.referencedColumns,
        onDelete: convertMysqlReferentialAction(row.on_delete),
        onUpdate: convertMysqlReferentialAction(row.on_update),
      })),
  };
};

/** One catalog row per constraint column and its referenced counterpart. */
type MysqlConstraint = {
  schema_name: string;
  table_name: string;
  constraint_name: string;
  constraint_type: "PRIMARY KEY" | "UNIQUE" | "FOREIGN KEY";
  column_name: string;
  referenced_table: string | null;
  referenced_column: string | null;
  on_delete: string | null;
  on_update: string | null;
};

/** Converts catalog referential actions to the schema API's lowercase values. */
export const convertMysqlReferentialAction = (action: string | null) => {
  const actionMap: Record<string, ReferentialActions> = {
    CASCADE: "cascade",
    "SET NULL": "set null",
    "SET DEFAULT": "set default",
    RESTRICT: "restrict",
    "NO ACTION": "no action",
  };
  return action ? actionMap[action] : undefined;
};
