import { SqliteDialect, sql } from "kysely";
import Database from "better-sqlite3";
import { IntrospectProps, KyrageDialect } from "./types";
import { DBClient, PlannableKysely } from "../client";
import { computeAutoGeneratedIndexesAndConstraints } from "./shared";
import {
  buildFileDevDatabaseConfig,
  FileDevDatabaseProvider,
} from "../dev/providers/file";
import { ReferentialActions } from "../operations/shared/types";
import { generatePrimaryKeyConstraintName } from "../naming";

export class SQLiteKyrageDialect implements KyrageDialect {
  getName() {
    return "sqlite" as const;
  }

  createKyselyDialect(connectionString: string) {
    return new SqliteDialect({
      database: new Database(connectionString),
    });
  }

  createIntrospectionDriver(client: DBClient) {
    return {
      convertTypeName: convertSQLiteTypeName,
      introspect: doSQLiteIntrospect(client),
    };
  }

  createDevDatabaseProvider() {
    return new FileDevDatabaseProvider();
  }

  parseDevDatabaseConfig(config: unknown) {
    // SQLite supports file-based dev databases only
    return buildFileDevDatabaseConfig().parse(config);
  }

  async hasReusableDevDatabase(): Promise<boolean> {
    // File-based dialects don't support reusable dev databases
    return false;
  }
}

export const doSQLiteIntrospect =
  (client: DBClient) => async (props: IntrospectProps) => {
    await using db = client.getDB();
    const [tables, indexes, constraints] = await Promise.all([
      introspectSQLiteTables(db),
      introspectSQLiteIndexes(db),
      introspectSQLiteConstraints(db),
    ]);
    const {
      indexes: normalizedIndexes,
      uniqueConstraints: normalizedUniqueConstraints,
    } = computeAutoGeneratedIndexesAndConstraints(props.config, {
      indexes,
      constraints,
    });

    return {
      tables,
      indexes: normalizedIndexes,
      constraints: {
        ...constraints,
        unique: normalizedUniqueConstraints,
      },
    };
  };

/*
 * Convert SQLite type names to more general SQL type names.
 * Also extract character maximum length from varchar types.
 */
export const convertSQLiteTypeName = (typeName: string) => {
  const nameDict: Record<string, string> = {
    INTEGER: "integer",
    TEXT: "text",
    REAL: "real",
    BLOB: "blob",
    NUMERIC: "numeric",
    INT8: "bigint",
    BOOLEAN: "boolean",
    VARCHAR: "varchar",
    CHAR: "char",
    UUID: "uuid",
  };

  // Extract length from varchar(n) or char(n)
  const varcharMatch = typeName.match(/^(varchar|char)\((\d+)\)$/i);
  if (varcharMatch) {
    return varcharMatch[1].toLowerCase();
  }

  // Try exact match first (case-insensitive)
  const upperTypeName = typeName.toUpperCase();
  if (nameDict[upperTypeName]) {
    return nameDict[upperTypeName];
  }

  // Return lowercase version as fallback
  return typeName.toLowerCase();
};

export const introspectSQLiteTables = async (db: PlannableKysely) => {
  // Get list of tables excluding sqlite system tables
  const { rows: tables } = await sql`
    SELECT name FROM sqlite_master 
    WHERE type = 'table' 
    AND name NOT LIKE 'sqlite_%'
    AND name != 'kysely_migration'
    AND name != 'kysely_migration_lock'
  `
    .$castTo<{ name: string }>()
    .execute(db);

  const tableInfos = [];

  for (const table of tables) {
    // Get column information for each table using PRAGMA table_info
    const { rows: columns } = await sql`
      SELECT * FROM pragma_table_info(${table.name})
    `
      .$castTo<SQLiteColumnInfo>()
      .execute(db);

    tableInfos.push(
      ...columns.map((col) => {
        // Extract character length from varchar(n) or char(n) types
        let characterMaximumLength: number | null = null;
        const varcharMatch = col.type.match(/^(?:varchar|char)\((\d+)\)$/i);
        if (varcharMatch) {
          characterMaximumLength = parseInt(varcharMatch[1], 10);
        }

        return {
          schema: "public", // Use "public" for consistency with PostgreSQL
          table: table.name,
          name: col.name,
          default: col.dflt_value,
          characterMaximumLength,
        };
      }),
    );
  }

  return tableInfos;
};

type SQLiteColumnInfo = {
  cid: number;
  name: string;
  type: string;
  notnull: number;
  dflt_value: string | null;
  pk: number;
};

export const introspectSQLiteIndexes = async (db: PlannableKysely) => {
  const { rows: tables } = await sql`
    SELECT name FROM sqlite_master 
    WHERE type = 'table' 
    AND name NOT LIKE 'sqlite_%'
    AND name != 'kysely_migration'
    AND name != 'kysely_migration_lock'
  `
    .$castTo<{ name: string }>()
    .execute(db);

  const indexes = [];

  for (const table of tables) {
    const { rows: indexList } = await sql`
      SELECT * FROM pragma_index_list(${table.name})
    `
      .$castTo<SQLiteIndexList>()
      .execute(db);

    for (const index of indexList) {
      // Only include indexes created by CREATE INDEX (origin 'c'), not auto-generated ones
      if (index.origin === "c") {
        const { rows: indexInfo } = await sql`
          SELECT * FROM pragma_index_info(${index.name})
        `
          .$castTo<SQLiteIndexInfo>()
          .execute(db);

        indexes.push({
          table: table.name,
          name: index.name,
          columns: indexInfo.map((info) => info.name),
          unique: index.unique === 1,
        });
      }
    }
  }

  return indexes.sort((a, b) => {
    if (a.table !== b.table) return a.table.localeCompare(b.table);
    return a.name.localeCompare(b.name);
  });
};

type SQLiteIndexList = {
  seq: number;
  name: string;
  unique: number;
  origin: string;
  partial: number;
};

type SQLiteIndexInfo = {
  seqno: number;
  cid: number;
  name: string;
};

export const introspectSQLiteConstraints = async (db: PlannableKysely) => {
  const { rows: tables } = await sql`
    SELECT name, sql FROM sqlite_master 
    WHERE type = 'table' 
    AND name NOT LIKE 'sqlite_%'
    AND name != 'kysely_migration'
    AND name != 'kysely_migration_lock'
  `
    .$castTo<{ name: string; sql: string | null }>()
    .execute(db);

  const primaryKeys = [];
  const uniqueConstraints: any[] = [];
  const foreignKeys: any[] = [];

  for (const table of tables) {
    // NOTE: SQLite's PRAGMA commands don't return constraint names.
    // Custom constraint names specified in CREATE TABLE are not preserved during introspection.
    // This is a known limitation of SQLite's metadata system.
    // Use 'kyrage lint' to check for dialect-specific behaviors.

    // Get primary key information
    const { rows: tableInfo } = await sql`
      SELECT * FROM pragma_table_info(${table.name})
    `
      .$castTo<SQLiteColumnInfo>()
      .execute(db);

    const pkColumns = tableInfo
      .filter((col) => col.pk > 0)
      .sort((a, b) => a.pk - b.pk)
      .map((col) => col.name);

    if (pkColumns.length > 0) {
      primaryKeys.push({
        schema: "public",
        table: table.name,
        name: generatePrimaryKeyConstraintName(table.name, pkColumns),
        type: "PRIMARY KEY" as const,
        columns: pkColumns,
        on_delete: null,
        on_update: null,
        referenced_columns: null,
        referenced_table: null,
      });
    }

    // Get foreign key information
    const { rows: fkList } = await sql`
      SELECT * FROM pragma_foreign_key_list(${table.name})
    `
      .$castTo<SQLiteForeignKey>()
      .execute(db);

    // Group foreign keys by id
    const fkGroups = fkList.reduce(
      (acc, fk) => {
        if (!acc[fk.id]) acc[fk.id] = [];
        acc[fk.id].push(fk);
        return acc;
      },
      {} as Record<number, SQLiteForeignKey[]>,
    );

    Object.entries(fkGroups).forEach(([, group]) => {
      const columns = group.map((fk) => fk.from);
      // Generate constraint name automatically (custom names are not preserved in SQLite)
      const fkName =
        group.length > 0 && group[0].from
          ? `fk_${group[0].from}`
          : `fk_${table.name}_${group[0].table}`;

      foreignKeys.push({
        schema: "public",
        table: table.name,
        name: fkName,
        type: "FOREIGN KEY" as const,
        columns,
        referencedTable: group[0].table,
        referencedColumns: group.map((fk) => fk.to),
        onDelete: mapSQLiteAction(group[0].on_delete),
        onUpdate: mapSQLiteAction(group[0].on_update),
      });
    });

    // Get unique constraint information from indexes
    const { rows: indexList } = await sql`
      SELECT * FROM pragma_index_list(${table.name})
    `
      .$castTo<SQLiteIndexList>()
      .execute(db);

    for (const index of indexList) {
      // Unique indexes with origin 'u' are unique constraints
      if (index.unique === 1 && index.origin === "u") {
        const { rows: indexInfo } = await sql`
          SELECT * FROM pragma_index_info(${index.name})
        `
          .$castTo<SQLiteIndexInfo>()
          .execute(db);

        const columns = indexInfo.map((info) => info.name);
        // Generate constraint name automatically (custom names are not preserved in SQLite)
        const constraintName =
          columns.length === 1
            ? `${table.name}_${columns[0]}_unique`
            : `uq_${table.name}_${columns.join("_")}`;

        uniqueConstraints.push({
          schema: "public",
          table: table.name,
          name: constraintName,
          type: "UNIQUE" as const,
          columns,
          on_delete: null,
          on_update: null,
          referenced_columns: null,
          referenced_table: null,
        });
      }
    }
  }

  return {
    primaryKey: primaryKeys.sort((a, b) => {
      if (a.table !== b.table) return a.table.localeCompare(b.table);
      return a.name.localeCompare(b.name);
    }),
    unique: uniqueConstraints.sort((a, b) => {
      if (a.table !== b.table) return a.table.localeCompare(b.table);
      return a.name.localeCompare(b.name);
    }),
    foreignKey: foreignKeys.sort((a, b) => {
      if (a.table !== b.table) return a.table.localeCompare(b.table);
      return a.name.localeCompare(b.name);
    }),
  };
};

type SQLiteForeignKey = {
  id: number;
  seq: number;
  table: string;
  from: string;
  to: string;
  on_update: string;
  on_delete: string;
  match: string;
};

const mapSQLiteAction = (action: string): ReferentialActions | undefined => {
  const actionMap: Record<string, ReferentialActions> = {
    CASCADE: "cascade",
    "SET NULL": "set null",
    "SET DEFAULT": "set default",
    RESTRICT: "restrict",
    "NO ACTION": "no action",
  };

  return actionMap[action.toUpperCase()];
};
