import { ColumnValue, DatabaseValue } from "../schema";
import { ColumnDataType } from "kysely";

/**
 * Defines a column in a table.
 */
export const column = (
  type: ColumnDataType,
  options?: Partial<Omit<ColumnValue, "type">>
) => ({
  type,
  notNull: options?.notNull,
  primaryKey: options?.primaryKey,
  unique: options?.unique,
  defaultSql: options?.defaultSql,
});

type DefinedColumn = ReturnType<typeof column>;

type DefinedIndex = {
  kind: "index";
  name: string;
  columns: string[];
  unique: boolean;
};

type ExpressionBuilders<T extends Record<string, DefinedColumn>> = {
  /**
   * Creates an index on the specified columns.
   *
   * The default is non-unique, and name is autogenerated by joining the column names and table name.
   */
  index: (
    columns: Array<keyof T>,
    options?: {
      name?: string;
      unique?: boolean;
    }
  ) => DefinedIndex;
};

/**
 * Defines a table with its columns and optional expression builders.
 */
export const defineTable = <T extends Record<string, DefinedColumn>>(
  /**
   * The name of the table.
   */
  name: string,

  /**
   * The columns in the table.
   */
  columns: T,

  /**
   * The expression builders for the table.
   *
   * This is where you can define additional indexes, constraints, or other
   * database-specific features for the table.
   */
  tableExpBuilder?: (
    builder: ExpressionBuilders<T>
  ) => Array<ReturnType<ExpressionBuilders<T>["index"]>>
) => {
  const indexBuilder: ExpressionBuilders<T>["index"] = (cols, options) => {
    const columnNames = cols.map(String);
    return {
      kind: "index",
      name: options?.name ?? `idx_${name}_${columnNames.join("_")}`,
      columns: columnNames,
      unique: options?.unique ?? false,
    };
  };

  const builtIndexes = tableExpBuilder
    ? tableExpBuilder({ index: indexBuilder })
    : [];

  return {
    tableName: name,
    columns,
    indexes: builtIndexes,
  };
};

export type DefinedTable = ReturnType<typeof defineTable> & {
  indexes: DefinedIndex[];
};
export type DefinedTables = Array<DefinedTable>;

export type DefineConfigProp = {
  database: DatabaseValue;
  tables: DefinedTables;
};

export const defineConfig = (config: DefineConfigProp) => {
  const indexMap = new Map<
    string,
    { table: string; name: string; columns: string[]; unique: boolean }
  >();
  for (const t of config.tables) {
    const tableName = t.tableName;
    const indexes: DefinedIndex[] = t.indexes ?? [];
    for (const ix of indexes) {
      indexMap.set(`${tableName}:${ix.name}`, {
        table: tableName,
        name: ix.name,
        columns: ix.columns,
        unique: ix.unique,
      });
    }
  }

  return {
    ...config,
    indexes: Array.from(indexMap.values()),
  } as const;
};
