name: Add Changeset to Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  add-changeset:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          node-version-file: './package.json'
      - run: pnpm install
      - name: Get first commit message and create changeset
        uses: actions/github-script@v7
        with:
          script: |
            const { default: writeChangeset }= require('@changesets/write');
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            // Check if any commit message starts with '[add changeset]'
            const hasChangesetCommit = commits.some(c => c.commit.message.startsWith('[add changeset]'));
            if (hasChangesetCommit) {
              console.log('PR already contains a changeset commit. Skipping changeset creation.');
              return;
            }

            // Get a commit message from the first line of the commit in the PR that dependabot created
            const firstCommit = commits[0];
            const commitMessage = firstCommit.commit.message.split('\n')[0];
            console.log('Commit message:', commitMessage);

            const id = await writeChangeset(
              {
                summary: commitMessage,
                releases: [
                  { name: "@izumisy/kyrage", type: "patch" }
                ]
              },
              process.cwd(),
            );

            console.log(`Created changeset with ID: ${id}`);
      - name: Commit changeset
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[add changeset] dependabot update'
          file_pattern: '.changeset/*.md'
