name: Test

on:
  push:
    paths-ignore:
      - '**/*.*md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          node-version-file: './package.json'
      - run: pnpm install
      - run: pnpm type-check

  test:
    needs: type-check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dialect:
          - postgres
          - cockroachdb
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          node-version-file: './package.json'
      - run: pnpm install
      - run: pnpm test
        env:
          TEST_DIALECT: ${{ matrix.dialect }}


